//! Logic for [`user`][crate::user] entity that is not generated by [`sea_orm`].

use sea_orm::{prelude::*, Set};

use crate::{user::*, Uuid};

impl ActiveModelBehavior for ActiveModel {
    /// Create a new `entry::ActiveModel` with a random id and default values.
    fn new() -> Self {
        Self {
            id: Set(Uuid::new_v4()),
            ..ActiveModelTrait::default()
        }
    }
}
