[workspace]
members = [
  "edid",
  "edihkal",
  "edihkal/migration",
  "edihkal-client",
  "edihkal_tracing",
  "entity",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/lazulit3/edihkal"
