[workspace]
members = ["edid", "edihkal", "edihkal-client", "edihkal_tracing", "entity", "edihkal/migration"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://0xacab.org/lazulite/edihkal"
