[package]
name = "entity"
version = "0.1.0"
publish = false
edition.license = true
edition.license-file = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dependencies.sea_skipper]
git = "https://github.com/lazulit3/sea_skipper.git"
rev = "ec9f7fb4301afdf78d82f9365a4009e33bb45e1"
features = ["derive", "derive-newmodel-with-serde"]

[dependencies.sea-orm]
default-features = false
features = ["macros", "with-chrono", "with-json", "with-uuid"]
version = "0.11"
