[package]
name = "edihkal-client"
version = "0.1.0"
edition = "2021"
description = "Client for edihkal API."

[dependencies]
edihkal-core = { version = "0.1.0", path = "../edihkal-core" }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.86"
thiserror = "1.0.37"
