[package]
name = "edihkal-core"
version = "0.1.0"
edition = "2021"
description = "Core library for the edihkal project."

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.86"
