[package]
name = "edihkal"
version = "0.1.0"
description = "Server for edihkal"
edition.repository = true
edition.workspace = true

[dependencies]
anyhow = "1.0.65"
axum = { version = "0.5.15", default-features = false, features = ["http1"] }
config = { version = "0.13.2", default-features = false, features = ["yaml"] }
serde = "1.0.145"
serde_json = "1.0.85"
sqlx = { version = "0.6.1", features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "migrate", "offline"], default-features = false }
tokio = { version = "1.20.1", features = ["macros"] }
uuid = { version = "1.1.2", features = ["v4"] }

edihkal-core = { version = "0.1.0", path = "../edihkal-core" }
tower-http = { version = "0.3.4", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["std", "env-filter", "smallvec", "parking_lot", "registry", "fmt"] }
tracing = "0.1.37"

[dev-dependencies]
axum-test-helper = "0.1.1"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
