[package]
name = "edid"
version = "0.1.0"
description = "A CLI client for edihkal."
edition.repository = true
edition.workspace = true

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.10", features = ["derive"] }
edihkal-client = { version = "0.1.0", path = "../edihkal-client" }
figment = { version = "0.10.8", features = ["env", "toml"] }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1.20.1", features = ["macros", "rt"] }

[dev-dependencies]
rstest = "0.15.0"
wiremock = "0.5.15"
