[package]
name = "edid"
version = "0.1.0"
edition = "2021"
description = "EDID: Every Drug I Did, a CLI client for EDIHKAL."

[dependencies]
clap = { version = "4.0.0-rc.3", features = ["derive"] }
config = { version = "0.13.2", default-features = false, features = ["yaml"] }
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.145", features = ["derive"] }
