[package]
name = "edid"
version = "0.1.0"
edition = "2021"
description = "A CLI client for edihkal."

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
config = { version = "0.13.2", default-features = false, features = ["yaml"] }
edihkal-core = { version = "0.1.0", path = "../edihkal-core" }
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1.20.1", features = ["macros", "rt"] }
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
rstest = "0.15.0"
wiremock = "0.5.15"
