# https://github.com/EmbarkStudios/cargo-deny-action#recommended-pipeline-if-using-advisories-to-avoid-sudden-breakages

name: audit
on:
  push:
    branches: ["develop"]
    paths:
      - '**/Cargo.*'
  pull_request:
    branches: ["develop"]
    paths:
      - '**/Cargo.*'
  schedule:
  - cron: '11 11 * * *'
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
