name: format

on:
  push:
    branches: ["develop"]
    paths:
      - '**.rs'
  pull_request:
    branches: ["develop"]
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --check
