//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

mod behavior;
pub mod drug;
pub mod entry;

pub use behavior::drug::NewDrug;
pub use behavior::entry::NewEntry;
pub use drug::Entity as Drug;
pub use entry::Entity as Entry;
