//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude;

pub mod drug;
pub mod entry;

// The code below is not generated by sea-orm-codegen and may need to be restored after updating the generated entities.
mod behavior;
pub mod uuid;

pub use crate::uuid::UuidV4 as Uuid;
