//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::drug::Entity as Drug;
pub use super::entry::Entity as Entry;

// The code below is not generated by sea-orm-codegen and may need to be restored after updating the generated entities.
pub use sea_orm_new_model::NewModelTrait;
